//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.Bill_Details = new HashSet<Bill_Details>();
        }
    
        public int bill_Id { get; set; }
        public string customer_Name { get; set; }
        public string customer_Mobile { get; set; }
        public string customer_Address { get; set; }
        public System.DateTime bill_Date { get; set; }
        public Nullable<int> pdt_Count { get; set; }
        public Nullable<int> pdt_QuantityCount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
    
        public virtual ICollection<Bill_Details> Bill_Details { get; set; }
    }
}
