//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Bill_Details = new HashSet<Bill_Details>();
        }
    
        public string Pdt_Id { get; set; }
        public string Pdt_Name { get; set; }
        public Nullable<decimal> Pdt_BuyPrice { get; set; }
        public Nullable<decimal> Pdt_GST { get; set; }
        public Nullable<decimal> Pdt_SellPrice { get; set; }
        public Nullable<decimal> Pdt_Discount { get; set; }
        public Nullable<System.DateTime> Pdt_PurchaseDate { get; set; }
        public Nullable<int> Pdt_Quantity { get; set; }
        public Nullable<bool> Pdt_Tax_Type { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created_DateTime { get; set; }
        public System.DateTime Updated_DateTime { get; set; }
    
        public virtual ICollection<Bill_Details> Bill_Details { get; set; }
    }
}
